import type { AIStatus } from '@gradion/shared/enums';

import { UserRole } from '@backend/modules/users/domain/user-role.enum';
import { ExpenseReportStatus } from '@backend/modules/reports/reports.types';

export interface SeedAccount {
  readonly email: string;
  readonly password: string;
  readonly role: UserRole;
}

export interface SeedReport {
  readonly id: string;
  readonly userEmail: string;
  readonly title: string;
  readonly description: string | null;
  readonly status: ExpenseReportStatus;
  readonly currency: string;
  readonly submittedAt: string | null;
  readonly approvedAt: string | null;
  readonly rejectedAt: string | null;
}

export interface SeedItem {
  readonly id: string;
  readonly reportId: string;
  readonly merchant: string | null;
  readonly description: string | null;
  readonly amount: number | null;
  readonly currency: string | null;
  readonly date: string | null;
  readonly category: string | null;
  readonly aiStatus: AIStatus;
  readonly aiExtracted: boolean;
}

// ─── Users ───────────────────────────────────────────────────────────────────

export const seedAccounts = [
  {
    email: 'admin@openai.com',
    password: 'password1!',
    role: UserRole.ADMIN,
  },
  {
    email: 'sarah@openai.com',
    password: 'Password1!',
    role: UserRole.USER,
  },
  {
    email: 'david@openai.com',
    password: 'Password1!',
    role: UserRole.USER,
  },
] as const satisfies readonly SeedAccount[];

// ─── Reports ─────────────────────────────────────────────────────────────────
// IDs: 019460ab-0002-7000-8000-0000000000XX  (01 – 30)

const R = (n: string) => `019460ab-0002-7000-8000-${n.padStart(12, '0')}`;

export const seedReports: readonly SeedReport[] = [
  // ── Ho Chi Minh City ───────────────────────────────────────────────────────
  {
    id: R('000000000001'),
    userEmail: 'sarah@openai.com',
    title: 'HCMC Business Development Q1 2025',
    description: 'Client meetings and business development activities in Ho Chi Minh City.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-15',
    approvedAt: '2025-01-28',
    rejectedAt: null,
  },
  {
    id: R('000000000002'),
    userEmail: 'sarah@openai.com',
    title: 'HCMC Client Hospitality Feb 2025',
    description: 'Client hospitality and entertainment expenses in Saigon.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-03-25',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000003'),
    userEmail: 'sarah@openai.com',
    title: 'Saigon Team Lunch Series Mar 2025',
    description: 'Weekly team lunches during March sprint cycle.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-10',
    approvedAt: '2025-03-18',
    rejectedAt: null,
  },
  {
    id: R('000000000004'),
    userEmail: 'sarah@openai.com',
    title: 'HCMC Sales Partner Dinner Apr 2025',
    description: 'Partner dinner with sales team in Ho Chi Minh City.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Hanoi ──────────────────────────────────────────────────────────────────
  {
    id: R('000000000005'),
    userEmail: 'sarah@openai.com',
    title: 'Hanoi Product Summit Q4 2024',
    description: 'Product summit and partner dinners during Q4 Hanoi visit.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-11-20',
    approvedAt: '2024-12-02',
    rejectedAt: null,
  },
  {
    id: R('000000000006'),
    userEmail: 'sarah@openai.com',
    title: 'Hanoi Engineering Offsite Mar 2025',
    description: 'Engineering team offsite and retrospective in Hanoi.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-01',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000007'),
    userEmail: 'sarah@openai.com',
    title: 'Hanoi Partnership Meeting Jan 2025',
    description: 'Partnership discussions and executive dinners in Hanoi.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-25',
    approvedAt: '2025-02-05',
    rejectedAt: null,
  },
  {
    id: R('000000000008'),
    userEmail: 'sarah@openai.com',
    title: 'Hanoi Team Dinner Feb 2025',
    description: 'Team dinner for cross-functional Hanoi meeting.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Central Vietnam ────────────────────────────────────────────────────────
  {
    id: R('000000000009'),
    userEmail: 'sarah@openai.com',
    title: 'Da Nang Sales Conference 2025',
    description: 'Annual sales conference and client dinners in Da Nang.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-20',
    approvedAt: '2025-03-01',
    rejectedAt: null,
  },
  {
    id: R('000000000010'),
    userEmail: 'sarah@openai.com',
    title: 'Hoi An Heritage Client Tour',
    description: 'Client heritage tour and meals in Hoi An Ancient Town.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-05',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000011'),
    userEmail: 'sarah@openai.com',
    title: 'Da Lat Annual Strategy Retreat',
    description: 'Annual leadership strategy retreat held in Da Lat.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-10',
    approvedAt: '2025-01-20',
    rejectedAt: null,
  },
  {
    id: R('000000000012'),
    userEmail: 'sarah@openai.com',
    title: 'Nha Trang Customer Success Retreat',
    description: 'Customer success team retreat in Nha Trang.',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2024-12-10',
    approvedAt: null,
    rejectedAt: '2024-12-20',
  },
  // ── Other Vietnam ──────────────────────────────────────────────────────────
  {
    id: R('000000000013'),
    userEmail: 'sarah@openai.com',
    title: 'Can Tho Mekong Delta Business Visit',
    description: 'Business visit and distributor meetings in Can Tho.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-12-15',
    approvedAt: '2024-12-28',
    rejectedAt: null,
  },
  {
    id: R('000000000014'),
    userEmail: 'sarah@openai.com',
    title: 'Vung Tau Client Platform Visit',
    description: 'Platform review and client entertainment in Vung Tau.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-10',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000015'),
    userEmail: 'sarah@openai.com',
    title: 'Phu Quoc Executive Leadership Retreat',
    description: 'Executive leadership retreat at Phu Quoc Island resort.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-05',
    approvedAt: '2025-02-18',
    rejectedAt: null,
  },
  {
    id: R('000000000016'),
    userEmail: 'sarah@openai.com',
    title: 'Hue Cultural Heritage Team Trip',
    description: 'Team cultural trip to Hue Imperial City.',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-02-15',
    approvedAt: null,
    rejectedAt: '2025-02-25',
  },
  // ── Japan ──────────────────────────────────────────────────────────────────
  {
    id: R('000000000017'),
    userEmail: 'sarah@openai.com',
    title: 'Tokyo Asia Product Summit Apr 2025',
    description: 'Asia product summit and executive partner dinners in Tokyo.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-05',
    approvedAt: '2025-04-12',
    rejectedAt: null,
  },
  {
    id: R('000000000018'),
    userEmail: 'sarah@openai.com',
    title: 'Tokyo Partnership Dinner Series',
    description: 'Series of fine dining partner dinners in Tokyo.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-15',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000019'),
    userEmail: 'sarah@openai.com',
    title: 'Osaka Tech Partner Visit',
    description: 'Technology partner site visit in Osaka.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Singapore ──────────────────────────────────────────────────────────────
  {
    id: R('000000000020'),
    userEmail: 'sarah@openai.com',
    title: 'Singapore FinTech Conference 2025',
    description: 'FinTech conference attendance and client entertainment in Singapore.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-20',
    approvedAt: '2025-03-28',
    rejectedAt: null,
  },
  {
    id: R('000000000021'),
    userEmail: 'sarah@openai.com',
    title: 'Singapore Regional HQ Business Trip',
    description: 'Regional HQ stakeholder meetings and client dinners in Singapore.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-12',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000022'),
    userEmail: 'sarah@openai.com',
    title: 'Singapore Client Entertainment',
    description: 'Client entertainment meals in Singapore.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Southeast Asia ─────────────────────────────────────────────────────────
  {
    id: R('000000000023'),
    userEmail: 'sarah@openai.com',
    title: 'Bangkok SEA Markets Meeting Q1 2025',
    description: 'Southeast Asia markets strategy meeting and client dinners in Bangkok.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-28',
    approvedAt: '2025-03-10',
    rejectedAt: null,
  },
  {
    id: R('000000000024'),
    userEmail: 'sarah@openai.com',
    title: 'Kuala Lumpur SEA HQ Visit',
    description: 'Southeast Asia HQ visit and executive partnership dinners in KL.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-30',
    approvedAt: '2025-02-10',
    rejectedAt: null,
  },
  {
    id: R('000000000025'),
    userEmail: 'sarah@openai.com',
    title: 'Bangkok Client Relations Visit',
    description: 'Client relationship building visit in Bangkok.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Korea ──────────────────────────────────────────────────────────────────
  {
    id: R('000000000026'),
    userEmail: 'sarah@openai.com',
    title: 'Seoul Tech Innovation Summit 2025',
    description: 'Technology innovation summit and partner networking in Seoul.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-15',
    approvedAt: '2025-03-22',
    rejectedAt: null,
  },
  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    id: R('000000000027'),
    userEmail: 'sarah@openai.com',
    title: 'Paris European Partnership Mar 2025',
    description: 'European partnership kickoff and client dinners in Paris.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000028'),
    userEmail: 'sarah@openai.com',
    title: 'London Investor Relations Apr 2025',
    description: 'Investor relations meetings and entertainment in London.',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-08',
    approvedAt: '2025-04-15',
    rejectedAt: null,
  },
  {
    id: R('000000000029'),
    userEmail: 'sarah@openai.com',
    title: 'Berlin Product Conference 2025',
    description: 'Product conference and partner networking in Berlin.',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Americas ───────────────────────────────────────────────────────────────
  {
    id: R('000000000030'),
    userEmail: 'sarah@openai.com',
    title: 'New York North America Launch',
    description: 'North America product launch event and investor dinners in New York.',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-17',
    approvedAt: null,
    rejectedAt: null,
  },

  // ── Vinh's 100 Reports (Q1-Q4 2025, global business development) ──────────────
  // IDs: 100-199 (distributed across all quarters and regions)
  // Status distribution: 40 APPROVED, 30 SUBMITTED, 20 DRAFT, 10 REJECTED
  // Locations: Vietnam (Hanoi, HCMC, Da Nang, Nha Trang), SE Asia, US/Europe, APAC
  // Currencies: VND, THB, SGD, MYR, IDR, USD, EUR, JPY, KRW, AUD, TWD
  {
    id: R('000000000100'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 01',
    description: 'Business development and client meetings in Hanoi - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-05',
    approvedAt: '2025-01-05',
    rejectedAt: null,
  },
  {
    id: R('000000000101'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 02',
    description: 'Business development and client meetings in Ho Chi Minh City - January 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-01-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000102'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 03',
    description: 'Business development and client meetings in Da Nang - January 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000103'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 04',
    description: 'Business development and client meetings in Nha Trang - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-14',
    approvedAt: '2025-01-14',
    rejectedAt: null,
  },
  {
    id: R('000000000104'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 05',
    description: 'Business development and client meetings in Hanoi - January 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-01-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000105'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 06',
    description: 'Business development and client meetings in Ho Chi Minh City - January 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000106'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 07',
    description: 'Business development and client meetings in Da Nang - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-23',
    approvedAt: '2025-01-23',
    rejectedAt: null,
  },
  {
    id: R('000000000107'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 08',
    description: 'Business development and client meetings in Nha Trang - January 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-01-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000108'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 09',
    description: 'Business development and client meetings in Hanoi - January 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000109'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 10',
    description: 'Business development and client meetings in Ho Chi Minh City - February 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-05',
    approvedAt: '2025-02-05',
    rejectedAt: null,
  },
  {
    id: R('000000000110'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 11',
    description: 'Business development and client meetings in Da Nang - February 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-02-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000111'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 12',
    description: 'Business development and client meetings in Nha Trang - February 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000112'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 13',
    description: 'Business development and client meetings in Hanoi - February 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-14',
    approvedAt: '2025-02-14',
    rejectedAt: null,
  },
  {
    id: R('000000000113'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 14',
    description: 'Business development and client meetings in Ho Chi Minh City - February 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-02-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000114'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 15',
    description: 'Business development and client meetings in Da Nang - February 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000115'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 16',
    description: 'Business development and client meetings in Nha Trang - February 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-23',
    approvedAt: '2025-02-23',
    rejectedAt: null,
  },
  {
    id: R('000000000116'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 17',
    description: 'Business development and client meetings in Hanoi - February 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-02-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000117'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 18',
    description: 'Business development and client meetings in Ho Chi Minh City - February 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000118'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 19',
    description: 'Business development and client meetings in Da Nang - March 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-05',
    approvedAt: '2025-03-05',
    rejectedAt: null,
  },
  {
    id: R('000000000119'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 20',
    description: 'Business development and client meetings in Nha Trang - March 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-03-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000120'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 21',
    description: 'Business development and client meetings in Hanoi - March 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000121'),
    userEmail: 'david@openai.com',
    title: 'Q1 HCMC Business Trip 22',
    description: 'Business development and client meetings in Ho Chi Minh City - March 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-14',
    approvedAt: '2025-03-14',
    rejectedAt: null,
  },
  {
    id: R('000000000122'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Business Trip 23',
    description: 'Business development and client meetings in Da Nang - March 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-03-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000123'),
    userEmail: 'david@openai.com',
    title: 'Q1 Nha Trang Business Trip 24',
    description: 'Business development and client meetings in Nha Trang - March 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000124'),
    userEmail: 'david@openai.com',
    title: 'Q1 Hanoi Business Trip 25',
    description: 'Business development and client meetings in Hanoi - March 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-03-23',
    approvedAt: '2025-03-23',
    rejectedAt: null,
  },
  {
    id: R('000000000125'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 01',
    description: 'Business development and client meetings in Bangkok - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-05',
    approvedAt: '2025-04-05',
    rejectedAt: null,
  },
  {
    id: R('000000000126'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 02',
    description: 'Business development and client meetings in Singapore - April 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000127'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 03',
    description: 'Business development and client meetings in Kuala Lumpur - April 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-04-11',
    approvedAt: null,
    rejectedAt: '2025-04-11',
  },
  {
    id: R('000000000128'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 04',
    description: 'Business development and client meetings in Jakarta - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-14',
    approvedAt: '2025-04-14',
    rejectedAt: null,
  },
  {
    id: R('000000000129'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 05',
    description: 'Business development and client meetings in Bangkok - April 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000205'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 06',
    description: 'Business development and client meetings in Singapore - April 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-04-20',
    approvedAt: null,
    rejectedAt: '2025-04-20',
  },
  {
    id: R('000000000201'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 07',
    description: 'Business development and client meetings in Kuala Lumpur - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-23',
    approvedAt: '2025-04-23',
    rejectedAt: null,
  },
  {
    id: R('000000000202'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 08',
    description: 'Business development and client meetings in Jakarta - April 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-04-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000203'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 09',
    description: 'Business development and client meetings in Bangkok - April 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-04-25',
    approvedAt: null,
    rejectedAt: '2025-04-25',
  },
  {
    id: R('000000000204'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 10',
    description: 'Business development and client meetings in Singapore - May 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-05-05',
    approvedAt: '2025-05-05',
    rejectedAt: null,
  },
  {
    id: R('000000000205'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 11',
    description: 'Business development and client meetings in Kuala Lumpur - May 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-05-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000206'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 12',
    description: 'Business development and client meetings in Jakarta - May 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-05-11',
    approvedAt: null,
    rejectedAt: '2025-05-11',
  },
  {
    id: R('000000000207'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 13',
    description: 'Business development and client meetings in Bangkok - May 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-05-14',
    approvedAt: '2025-05-14',
    rejectedAt: null,
  },
  {
    id: R('000000000208'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 14',
    description: 'Business development and client meetings in Singapore - May 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-05-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000209'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 15',
    description: 'Business development and client meetings in Kuala Lumpur - May 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-05-20',
    approvedAt: null,
    rejectedAt: '2025-05-20',
  },
  {
    id: R('000000000210'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 16',
    description: 'Business development and client meetings in Jakarta - May 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-05-23',
    approvedAt: '2025-05-23',
    rejectedAt: null,
  },
  {
    id: R('000000000211'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 17',
    description: 'Business development and client meetings in Bangkok - May 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-05-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000212'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 18',
    description: 'Business development and client meetings in Singapore - May 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-05-25',
    approvedAt: null,
    rejectedAt: '2025-05-25',
  },
  {
    id: R('000000000213'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 19',
    description: 'Business development and client meetings in Kuala Lumpur - June 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-06-05',
    approvedAt: '2025-06-05',
    rejectedAt: null,
  },
  {
    id: R('000000000214'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 20',
    description: 'Business development and client meetings in Jakarta - June 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-06-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000215'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 21',
    description: 'Business development and client meetings in Bangkok - June 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-06-11',
    approvedAt: null,
    rejectedAt: '2025-06-11',
  },
  {
    id: R('000000000216'),
    userEmail: 'david@openai.com',
    title: 'Q2 Singapore Business Trip 22',
    description: 'Business development and client meetings in Singapore - June 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-06-14',
    approvedAt: '2025-06-14',
    rejectedAt: null,
  },
  {
    id: R('000000000217'),
    userEmail: 'david@openai.com',
    title: 'Q2 KL Business Trip 23',
    description: 'Business development and client meetings in Kuala Lumpur - June 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-06-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000218'),
    userEmail: 'david@openai.com',
    title: 'Q2 Jakarta Business Trip 24',
    description: 'Business development and client meetings in Jakarta - June 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-06-20',
    approvedAt: null,
    rejectedAt: '2025-06-20',
  },
  {
    id: R('000000000219'),
    userEmail: 'david@openai.com',
    title: 'Q2 Bangkok Business Trip 25',
    description: 'Business development and client meetings in Bangkok - June 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-06-23',
    approvedAt: '2025-06-23',
    rejectedAt: null,
  },
  {
    id: R('000000000220'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 01',
    description: 'Business development and client meetings in New York - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-05',
    approvedAt: '2025-07-05',
    rejectedAt: null,
  },
  {
    id: R('000000000221'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 02',
    description: 'Business development and client meetings in San Francisco - July 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-07-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000222'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 03',
    description: 'Business development and client meetings in London - July 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000223'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 04',
    description: 'Business development and client meetings in Paris - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-14',
    approvedAt: '2025-07-14',
    rejectedAt: null,
  },
  {
    id: R('000000000224'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 05',
    description: 'Business development and client meetings in New York - July 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-07-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000225'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 06',
    description: 'Business development and client meetings in San Francisco - July 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000226'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 07',
    description: 'Business development and client meetings in London - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-23',
    approvedAt: '2025-07-23',
    rejectedAt: null,
  },
  {
    id: R('000000000227'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 08',
    description: 'Business development and client meetings in Paris - July 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-07-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000228'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 09',
    description: 'Business development and client meetings in New York - July 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000229'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 10',
    description: 'Business development and client meetings in San Francisco - August 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-08-05',
    approvedAt: '2025-08-05',
    rejectedAt: null,
  },
  {
    id: R('000000000230'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 11',
    description: 'Business development and client meetings in London - August 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-08-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000231'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 12',
    description: 'Business development and client meetings in Paris - August 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000232'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 13',
    description: 'Business development and client meetings in New York - August 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-08-14',
    approvedAt: '2025-08-14',
    rejectedAt: null,
  },
  {
    id: R('000000000233'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 14',
    description: 'Business development and client meetings in San Francisco - August 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-08-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000234'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 15',
    description: 'Business development and client meetings in London - August 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000235'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 16',
    description: 'Business development and client meetings in Paris - August 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-08-23',
    approvedAt: '2025-08-23',
    rejectedAt: null,
  },
  {
    id: R('000000000236'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 17',
    description: 'Business development and client meetings in New York - August 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-08-26',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000237'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 18',
    description: 'Business development and client meetings in San Francisco - August 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000238'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 19',
    description: 'Business development and client meetings in London - September 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-09-05',
    approvedAt: '2025-09-05',
    rejectedAt: null,
  },
  {
    id: R('000000000239'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 20',
    description: 'Business development and client meetings in Paris - September 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-09-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000240'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 21',
    description: 'Business development and client meetings in New York - September 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000241'),
    userEmail: 'david@openai.com',
    title: 'Q3 SF Business Trip 22',
    description: 'Business development and client meetings in San Francisco - September 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-09-14',
    approvedAt: '2025-09-14',
    rejectedAt: null,
  },
  {
    id: R('000000000242'),
    userEmail: 'david@openai.com',
    title: 'Q3 London Business Trip 23',
    description: 'Business development and client meetings in London - September 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-09-17',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000243'),
    userEmail: 'david@openai.com',
    title: 'Q3 Paris Business Trip 24',
    description: 'Business development and client meetings in Paris - September 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000244'),
    userEmail: 'david@openai.com',
    title: 'Q3 NYC Business Trip 25',
    description: 'Business development and client meetings in New York - September 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-09-23',
    approvedAt: '2025-09-23',
    rejectedAt: null,
  },
  {
    id: R('000000000245'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 01',
    description: 'Business development and client meetings in Tokyo - October 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-10-05',
    approvedAt: '2025-10-05',
    rejectedAt: null,
  },
  {
    id: R('000000000246'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 02',
    description: 'Business development and client meetings in Seoul - October 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000247'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 03',
    description: 'Business development and client meetings in Sydney - October 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-10-11',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000248'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 04',
    description: 'Business development and client meetings in Taipei - October 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-10-14',
    approvedAt: '2025-10-14',
    rejectedAt: null,
  },
  {
    id: R('000000000249'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 05',
    description: 'Business development and client meetings in Tokyo - October 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000250'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 06',
    description: 'Business development and client meetings in Seoul - October 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-10-20',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000181'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 07',
    description: 'Business development and client meetings in Sydney - October 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-10-23',
    approvedAt: '2025-10-23',
    rejectedAt: null,
  },
  {
    id: R('000000000182'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 08',
    description: 'Business development and client meetings in Taipei - October 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000183'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 09',
    description: 'Business development and client meetings in Tokyo - October 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-10-25',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000184'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 10',
    description: 'Business development and client meetings in Seoul - November 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-11-05',
    approvedAt: '2025-11-05',
    rejectedAt: null,
  },
  {
    id: R('000000000185'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 11',
    description: 'Business development and client meetings in Sydney - November 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000186'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 12',
    description: 'Business development and client meetings in Taipei - November 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-11-11',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000187'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 13',
    description: 'Business development and client meetings in Tokyo - November 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-11-14',
    approvedAt: '2025-11-14',
    rejectedAt: null,
  },
  {
    id: R('000000000188'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 14',
    description: 'Business development and client meetings in Seoul - November 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000189'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 15',
    description: 'Business development and client meetings in Sydney - November 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-11-20',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000190'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 16',
    description: 'Business development and client meetings in Taipei - November 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-11-23',
    approvedAt: '2025-11-23',
    rejectedAt: null,
  },
  {
    id: R('000000000191'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 17',
    description: 'Business development and client meetings in Tokyo - November 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000192'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 18',
    description: 'Business development and client meetings in Seoul - November 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-11-25',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000193'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 19',
    description: 'Business development and client meetings in Sydney - December 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-12-05',
    approvedAt: '2025-12-05',
    rejectedAt: null,
  },
  {
    id: R('000000000194'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 20',
    description: 'Business development and client meetings in Taipei - December 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000195'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 21',
    description: 'Business development and client meetings in Tokyo - December 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-12-11',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000196'),
    userEmail: 'david@openai.com',
    title: 'Q4 Seoul Business Trip 22',
    description: 'Business development and client meetings in Seoul - December 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-12-14',
    approvedAt: '2025-12-14',
    rejectedAt: null,
  },
  {
    id: R('000000000197'),
    userEmail: 'david@openai.com',
    title: 'Q4 Sydney Business Trip 23',
    description: 'Business development and client meetings in Sydney - December 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000198'),
    userEmail: 'david@openai.com',
    title: 'Q4 Taipei Business Trip 24',
    description: 'Business development and client meetings in Taipei - December 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-12-20',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000199'),
    userEmail: 'david@openai.com',
    title: 'Q4 Tokyo Business Trip 25',
    description: 'Business development and client meetings in Tokyo - December 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-12-23',
    approvedAt: '2025-12-23',
    rejectedAt: null,
  },
  // ── Vinh's Additional 50 Reports (2024-2025) ─────────────────────────────────
  {
    id: R('000000000201'),
    userEmail: 'david@openai.com',
    title: 'Q1 San Francisco Business Trip 26',
    description: 'Client meetings and product demo in San Francisco - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-10',
    approvedAt: '2025-01-12',
    rejectedAt: null,
  },
  {
    id: R('000000000202'),
    userEmail: 'david@openai.com',
    title: 'Q1 New York Business Trip 27',
    description: 'Investor meetings in New York City - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-15',
    approvedAt: '2025-01-17',
    rejectedAt: null,
  },
  {
    id: R('000000000203'),
    userEmail: 'david@openai.com',
    title: 'Q1 Los Angeles Business Trip 28',
    description: 'Partnership discussions in Los Angeles - February 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-02-20',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000204'),
    userEmail: 'david@openai.com',
    title: 'Q1 Seattle Tech Visit 29',
    description: 'Tech company visit and collaboration talks in Seattle - February 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-02-25',
    approvedAt: '2025-02-27',
    rejectedAt: null,
  },
  {
    id: R('000000000205'),
    userEmail: 'david@openai.com',
    title: 'Q1 Boston Healthcare Conference 30',
    description: 'Healthcare tech conference attendance in Boston - March 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000206'),
    userEmail: 'david@openai.com',
    title: 'Q2 London Financial Summit 31',
    description: 'Financial technology summit in London - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-05',
    approvedAt: '2025-04-08',
    rejectedAt: null,
  },
  {
    id: R('000000000207'),
    userEmail: 'david@openai.com',
    title: 'Q2 Paris Partner Meeting 32',
    description: 'European partner strategy meeting in Paris - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-12',
    approvedAt: '2025-04-15',
    rejectedAt: null,
  },
  {
    id: R('000000000208'),
    userEmail: 'david@openai.com',
    title: 'Q2 Berlin Tech Hub Visit 33',
    description: 'Technology hub exploration in Berlin - May 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-05-10',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000209'),
    userEmail: 'david@openai.com',
    title: 'Q2 Amsterdam Innovation Expo 34',
    description: 'Innovation expo and networking in Amsterdam - May 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000210'),
    userEmail: 'david@openai.com',
    title: 'Q2 Dublin Software Summit 35',
    description: 'Software summit attendance in Dublin - June 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-06-01',
    approvedAt: '2025-06-04',
    rejectedAt: null,
  },
  {
    id: R('000000000211'),
    userEmail: 'david@openai.com',
    title: 'Q3 Sydney Business Development 36',
    description: 'APAC business development in Sydney - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-05',
    approvedAt: '2025-07-08',
    rejectedAt: null,
  },
  {
    id: R('000000000212'),
    userEmail: 'david@openai.com',
    title: 'Q3 Melbourne Partner Visits 37',
    description: 'Partner company visits in Melbourne - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-12',
    approvedAt: '2025-07-15',
    rejectedAt: null,
  },
  {
    id: R('000000000213'),
    userEmail: 'david@openai.com',
    title: 'Q3 Auckland Trade Show 38',
    description: 'Trade show participation in Auckland - August 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-08-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000214'),
    userEmail: 'david@openai.com',
    title: 'Q3 Singapore Tech Conference 39',
    description: 'Regional tech conference in Singapore - August 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000215'),
    userEmail: 'david@openai.com',
    title: 'Q3 Bangkok Regional Meeting 40',
    description: 'Southeast Asia regional meeting in Bangkok - September 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-09-01',
    approvedAt: '2025-09-04',
    rejectedAt: null,
  },
  {
    id: R('000000000216'),
    userEmail: 'david@openai.com',
    title: 'Q3 Kuala Lumpur Client Event 41',
    description: 'Client appreciation event in Kuala Lumpur - September 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-09-15',
    approvedAt: '2025-09-18',
    rejectedAt: null,
  },
  {
    id: R('000000000217'),
    userEmail: 'david@openai.com',
    title: 'Q3 Jakarta Partnership Summit 42',
    description: 'Partnership summit in Jakarta - October 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-10-05',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000218'),
    userEmail: 'david@openai.com',
    title: 'Q3 Manila Business Trip 43',
    description: 'Business development in Manila - October 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-10-12',
    approvedAt: null,
    rejectedAt: '2025-10-15',
  },
  {
    id: R('000000000219'),
    userEmail: 'david@openai.com',
    title: 'Q4 Toronto Financial Forum 44',
    description: 'Financial forum in Toronto - November 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-11-01',
    approvedAt: '2025-11-04',
    rejectedAt: null,
  },
  {
    id: R('000000000220'),
    userEmail: 'david@openai.com',
    title: 'Q4 Vancouver Tech Week 45',
    description: 'Technology week event in Vancouver - November 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-11-10',
    approvedAt: '2025-11-13',
    rejectedAt: null,
  },
  {
    id: R('000000000221'),
    userEmail: 'david@openai.com',
    title: 'Q4 Montreal AI Conference 46',
    description: 'AI conference in Montreal - November 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-11-20',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000222'),
    userEmail: 'david@openai.com',
    title: 'Q4 Dubai Innovation Summit 47',
    description: 'Innovation summit in Dubai - December 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000223'),
    userEmail: 'david@openai.com',
    title: 'Q4 Abu Dhabi Business Forum 48',
    description: 'Business forum in Abu Dhabi - December 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-12-05',
    approvedAt: '2025-12-08',
    rejectedAt: null,
  },
  {
    id: R('000000000224'),
    userEmail: 'david@openai.com',
    title: 'Q4 Mumbai Tech Summit 49',
    description: 'Technology summit in Mumbai - December 2025',
    status: ExpenseReportStatus.REJECTED,
    currency: 'USD',
    submittedAt: '2025-12-12',
    approvedAt: null,
    rejectedAt: '2025-12-15',
  },
  {
    id: R('000000000225'),
    userEmail: 'david@openai.com',
    title: 'Q4 Bangalore Innovation Hub 50',
    description: 'Innovation hub visit in Bangalore - December 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-12-18',
    approvedAt: null,
    rejectedAt: null,
  },
  // ── Additional Reports to reach 120 ────────────────────────────────
  {
    id: R('000000000251'),
    userEmail: 'david@openai.com',
    title: 'Q1 Ha Noi Office Visit 51',
    description: 'Office visit and team meeting in Ha Noi - January 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-01-10',
    approvedAt: '2024-01-12',
    rejectedAt: null,
  },
  {
    id: R('000000000252'),
    userEmail: 'david@openai.com',
    title: 'Q1 TP HCM Client Event 52',
    description: 'Client appreciation event in Ho Chi Minh City - February 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-02-15',
    approvedAt: '2024-02-18',
    rejectedAt: null,
  },
  {
    id: R('000000000253'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Partner Meeting 53',
    description: 'Partner meeting in Da Nang - March 2024',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2024-03-08',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000254'),
    userEmail: 'david@openai.com',
    title: 'Q2 Ha Noi Training 54',
    description: 'Team training session in Ha Noi - April 2024',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000255'),
    userEmail: 'david@openai.com',
    title: 'Q2 TP HCM Workshop 55',
    description: 'Workshop in Ho Chi Minh City - May 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-05-12',
    approvedAt: '2024-05-15',
    rejectedAt: null,
  },
  {
    id: R('000000000256'),
    userEmail: 'david@openai.com',
    title: 'Q2 Da Nang Seminar 56',
    description: 'Industry seminar in Da Nang - June 2024',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2024-06-05',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000257'),
    userEmail: 'david@openai.com',
    title: 'Q3 Ha Noi Conference 57',
    description: 'Annual conference in Ha Noi - July 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-07-20',
    approvedAt: '2024-07-23',
    rejectedAt: null,
  },
  {
    id: R('000000000258'),
    userEmail: 'david@openai.com',
    title: 'Q3 TP HCM Summit 58',
    description: 'Business summit in Ho Chi Minh City - August 2024',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000259'),
    userEmail: 'david@openai.com',
    title: 'Q3 Da Nang Retreat 59',
    description: 'Team retreat in Da Nang - September 2024',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2024-09-10',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000260'),
    userEmail: 'david@openai.com',
    title: 'Q4 Ha Noi Year End 60',
    description: 'Year-end meeting in Ha Noi - October 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-10-15',
    approvedAt: '2024-10-18',
    rejectedAt: null,
  },
  {
    id: R('000000000261'),
    userEmail: 'david@openai.com',
    title: 'Q4 TP HCM Review 61',
    description: 'Annual review in Ho Chi Minh City - November 2024',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2024-11-08',
    approvedAt: '2024-11-12',
    rejectedAt: null,
  },
  {
    id: R('000000000262'),
    userEmail: 'david@openai.com',
    title: 'Q4 Da Nang Planning 62',
    description: 'Planning meeting in Da Nang - December 2024',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000263'),
    userEmail: 'david@openai.com',
    title: 'Q1 Ha Noi Kickoff 63',
    description: 'Q1 kickoff meeting in Ha Noi - January 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-01-05',
    approvedAt: '2025-01-08',
    rejectedAt: null,
  },
  {
    id: R('000000000264'),
    userEmail: 'david@openai.com',
    title: 'Q1 TP HCM Launch 64',
    description: 'Product launch in Ho Chi Minh City - February 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-02-12',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000265'),
    userEmail: 'david@openai.com',
    title: 'Q1 Da Nang Update 65',
    description: 'Quarterly update in Da Nang - March 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000266'),
    userEmail: 'david@openai.com',
    title: 'Q2 Ha Noi Strategy 66',
    description: 'Strategy session in Ha Noi - April 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-04-10',
    approvedAt: '2025-04-13',
    rejectedAt: null,
  },
  {
    id: R('000000000267'),
    userEmail: 'david@openai.com',
    title: 'Q2 TP HCM Review 67',
    description: 'Mid-year review in Ho Chi Minh City - May 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-05-15',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000268'),
    userEmail: 'david@openai.com',
    title: 'Q2 Da Nang Workshop 68',
    description: 'Workshop in Da Nang - June 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000269'),
    userEmail: 'david@openai.com',
    title: 'Q3 Nha Trang Team 69',
    description: 'Team building in Nha Trang - July 2025',
    status: ExpenseReportStatus.APPROVED,
    currency: 'USD',
    submittedAt: '2025-07-08',
    approvedAt: '2025-07-10',
    rejectedAt: null,
  },
  {
    id: R('000000000270'),
    userEmail: 'david@openai.com',
    title: 'Q3 Can Tho Visit 70',
    description: 'Client visit in Can Tho - August 2025',
    status: ExpenseReportStatus.SUBMITTED,
    currency: 'USD',
    submittedAt: '2025-08-12',
    approvedAt: null,
    rejectedAt: null,
  },
  {
    id: R('000000000271'),
    userEmail: 'david@openai.com',
    title: 'Q3 Vung Tau Trip 71',
    description: 'Beach resort meeting in Vung Tau - September 2025',
    status: ExpenseReportStatus.DRAFT,
    currency: 'USD',
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
  },
];

// ─── Items ────────────────────────────────────────────────────────────────────
// IDs: 019460ab-0003-7000-8000-000000000XXX  (001 – 115)

const I = (n: string) => `019460ab-0003-7000-8000-${n.padStart(12, '0')}`;
const rid = (n: string) => R(n.padStart(12, '0'));

const PENDING_ITEM = (id: string, reportId: string): SeedItem => ({
  id,
  reportId,
  merchant: null,
  description: null,
  amount: null,
  currency: null,
  date: null,
  category: null,
  aiStatus: 'PENDING',
  aiExtracted: false,
});

const GENERATED_MERCHANTS = ['Highlands Coffee', "Pizza 4P's", "L'Usine", 'Annam Gourmet'] as const;

const GENERATED_CATEGORIES = [
  'Coffee & Refreshments',
  'Meals & Entertainment',
  'Client Meeting',
  'Local Transport',
] as const;

const extractSeedReportNumber = (reportId: string) => Number(reportId.slice(-12));

const makeGeneratedItem = (report: SeedReport, itemIndex: number): SeedItem => {
  const reportNumber = extractSeedReportNumber(report.id);
  const merchant = GENERATED_MERCHANTS[(reportNumber + itemIndex) % GENERATED_MERCHANTS.length]!;
  const category = GENERATED_CATEGORIES[(reportNumber + itemIndex) % GENERATED_CATEGORIES.length]!;
  const month = String((reportNumber % 12) + 1).padStart(2, '0');
  const day = String(((reportNumber + itemIndex * 3) % 24) + 1).padStart(2, '0');

  return {
    id: I(String(500000000000 + reportNumber * 10 + itemIndex)),
    reportId: report.id,
    merchant,
    description: `${category} for ${report.title}`,
    amount: 24 + ((reportNumber + itemIndex * 17) % 180),
    currency: report.currency,
    date: `2025-${month}-${day}`,
    category,
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  };
};

const generateMissingReportItems = (items: readonly SeedItem[]): SeedItem[] => {
  const seededReportIds = new Set(items.map((item) => item.reportId));
  const seenReportIds = new Set<string>();
  const generatedItems: SeedItem[] = [];

  for (const report of seedReports) {
    if (seenReportIds.has(report.id)) {
      continue;
    }

    seenReportIds.add(report.id);

    if (seededReportIds.has(report.id)) {
      continue;
    }

    generatedItems.push(makeGeneratedItem(report, 1), makeGeneratedItem(report, 2));
  }

  return generatedItems;
};

const baseSeedItems: readonly SeedItem[] = [
  // ── R01: HCMC Business Development Q1 2025 (APPROVED, VND) ─────────────────
  {
    id: I('000000000001'),
    reportId: rid('000000000001'),
    merchant: 'Nhà Hàng Ngon',
    description: 'Welcome dinner — 4 HCMC clients',
    amount: 100,
    currency: 'USD',
    date: '2025-01-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000002'),
    reportId: rid('000000000001'),
    merchant: "L'Usine Le Loi",
    description: 'Working breakfast — client onboarding session',
    amount: 28,
    currency: 'USD',
    date: '2025-01-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000003'),
    reportId: rid('000000000001'),
    merchant: 'Phúc Long Coffee & Tea',
    description: 'Team coffee strategy session (6 people)',
    amount: 15,
    currency: 'USD',
    date: '2025-01-10',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000004'),
    reportId: rid('000000000001'),
    merchant: "Pizza 4P's",
    description: 'Team lunch — mid-project debrief',
    amount: 54,
    currency: 'USD',
    date: '2025-01-11',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000005'),
    reportId: rid('000000000001'),
    merchant: 'Anan Saigon',
    description: 'Partner closing dinner — deal signed',
    amount: 157,
    currency: 'USD',
    date: '2025-01-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R02: HCMC Client Hospitality Feb 2025 (SUBMITTED, VND) ─────────────────
  {
    id: I('000000000006'),
    reportId: rid('000000000002'),
    merchant: 'The Refinery',
    description: 'European lunch with client delegation (5 pax)',
    amount: 77,
    currency: 'USD',
    date: '2025-02-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000007'),
    reportId: rid('000000000002'),
    merchant: 'Cục Gạch Quán',
    description: 'Traditional Vietnamese dinner — cultural experience',
    amount: 88,
    currency: 'USD',
    date: '2025-02-13',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000008'),
    reportId: rid('000000000002'),
    merchant: 'Highlands Coffee Saigon',
    description: 'Coffee meeting — pre-demo brief',
    amount: 10,
    currency: 'USD',
    date: '2025-02-14',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000009'),
    reportId: rid('000000000002'),
    merchant: 'Bếp Mẹ Ỉn',
    description: 'Home-style farewell lunch for client team',
    amount: 59,
    currency: 'USD',
    date: '2025-02-14',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R03: Saigon Team Lunch Series (APPROVED, VND) ──────────────────────────
  {
    id: I('000000000010'),
    reportId: rid('000000000003'),
    merchant: 'Quán Bún Bò Bà Ngọ',
    description: 'Team bún bò Huế lunch — weekly ritual',
    amount: 20,
    currency: 'USD',
    date: '2025-03-03',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000011'),
    reportId: rid('000000000003'),
    merchant: 'Nhà Hàng Ngon',
    description: 'Weekly team lunch — sprint planning',
    amount: 67,
    currency: 'USD',
    date: '2025-03-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000012'),
    reportId: rid('000000000003'),
    merchant: 'Phúc Long Coffee & Tea',
    description: 'Team coffee catch-up (8 people)',
    amount: 17,
    currency: 'USD',
    date: '2025-03-12',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000013'),
    reportId: rid('000000000003'),
    merchant: "Pizza 4P's",
    description: 'Sprint retrospective lunch',
    amount: 52,
    currency: 'USD',
    date: '2025-03-17',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000014'),
    reportId: rid('000000000003'),
    merchant: 'Cà Phê Trung Nguyên Legend',
    description: 'End-of-month team coffee debrief',
    amount: 14,
    currency: 'USD',
    date: '2025-03-24',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R04: HCMC Sales Partner Dinner (DRAFT) — PENDING ──────────────────────
  PENDING_ITEM(I('000000000015'), rid('000000000004')),
  PENDING_ITEM(I('000000000016'), rid('000000000004')),
  // ── R05: Hanoi Product Summit Q4 2024 (APPROVED, VND) ─────────────────────
  {
    id: I('000000000017'),
    reportId: rid('000000000005'),
    merchant: 'Bún Chả Hương Liên',
    description: 'Team lunch at the Obama spot',
    amount: 39,
    currency: 'USD',
    date: '2024-11-11',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000018'),
    reportId: rid('000000000005'),
    merchant: 'Chả Cá Lã Vọng',
    description: 'Summit dinner — iconic 140-year-old Hanoi restaurant',
    amount: 131,
    currency: 'USD',
    date: '2024-11-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000019'),
    reportId: rid('000000000005'),
    merchant: 'Giang Cafe (Cà Phê Trứng)',
    description: "Morning egg coffee session — inventor's original cafe",
    amount: 12,
    currency: 'USD',
    date: '2024-11-13',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000020'),
    reportId: rid('000000000005'),
    merchant: 'La Badiane',
    description: 'French-Vietnamese executive lunch',
    amount: 112,
    currency: 'USD',
    date: '2024-11-13',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000021'),
    reportId: rid('000000000005'),
    merchant: 'Phở Thìn',
    description: 'Traditional Hanoi pho — team breakfast',
    amount: 22,
    currency: 'USD',
    date: '2024-11-14',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R06: Hanoi Engineering Offsite (SUBMITTED, VND) ───────────────────────
  {
    id: I('000000000022'),
    reportId: rid('000000000006'),
    merchant: 'Cafe Đinh',
    description: 'Offsite kickoff egg coffee (6 engineers)',
    amount: 20,
    currency: 'USD',
    date: '2025-03-20',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000023'),
    reportId: rid('000000000006'),
    merchant: 'Chả Cá Thăng Long',
    description: 'Traditional grilled fish dinner',
    amount: 118,
    currency: 'USD',
    date: '2025-03-20',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000024'),
    reportId: rid('000000000006'),
    merchant: 'Home Kitchen',
    description: 'Homestyle team dinner — team bonding',
    amount: 71,
    currency: 'USD',
    date: '2025-03-21',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000025'),
    reportId: rid('000000000006'),
    merchant: 'Bún Chả Hương Liên',
    description: 'Working lunch — Agile retrospective',
    amount: 49,
    currency: 'USD',
    date: '2025-03-22',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R07: Hanoi Partnership Meeting (APPROVED, VND) ─────────────────────────
  {
    id: I('000000000026'),
    reportId: rid('000000000007'),
    merchant: 'La Badiane',
    description: 'Executive partnership lunch (6 pax)',
    amount: 171,
    currency: 'USD',
    date: '2025-01-15',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000027'),
    reportId: rid('000000000007'),
    merchant: 'Giang Cafe (Cà Phê Trứng)',
    description: 'Pre-meeting coffee brief',
    amount: 14,
    currency: 'USD',
    date: '2025-01-16',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000028'),
    reportId: rid('000000000007'),
    merchant: 'Chả Cá Lã Vọng',
    description: 'Partnership celebration dinner',
    amount: 147,
    currency: 'USD',
    date: '2025-01-16',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000029'),
    reportId: rid('000000000007'),
    merchant: 'Phở Thìn',
    description: 'Team breakfast — Day 2',
    amount: 29,
    currency: 'USD',
    date: '2025-01-17',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000030'),
    reportId: rid('000000000007'),
    merchant: 'The Old Hanoi',
    description: 'Farewell aperitif with partners',
    amount: 76,
    currency: 'USD',
    date: '2025-01-17',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R08: Hanoi Team Dinner (DRAFT) — PENDING ──────────────────────────────
  PENDING_ITEM(I('000000000031'), rid('000000000008')),
  PENDING_ITEM(I('000000000032'), rid('000000000008')),
  // ── R09: Da Nang Sales Conference (APPROVED, VND) ──────────────────────────
  {
    id: I('000000000033'),
    reportId: rid('000000000009'),
    merchant: 'Madame Lan',
    description: 'Opening night conference dinner (8 pax)',
    amount: 141,
    currency: 'USD',
    date: '2025-02-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000034'),
    reportId: rid('000000000009'),
    merchant: 'Waterfront Restaurant & Bar',
    description: 'Client lunch — Han River riverside',
    amount: 86,
    currency: 'USD',
    date: '2025-02-11',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000035'),
    reportId: rid('000000000009'),
    merchant: 'The Warehouse',
    description: 'Team drinks & tapas — networking session',
    amount: 69,
    currency: 'USD',
    date: '2025-02-11',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000036'),
    reportId: rid('000000000009'),
    merchant: 'Bread of Life',
    description: 'Networking seafood lunch',
    amount: 80,
    currency: 'USD',
    date: '2025-02-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000037'),
    reportId: rid('000000000009'),
    merchant: 'Bé Mặn',
    description: 'Local Da Nang cuisine farewell dinner',
    amount: 114,
    currency: 'USD',
    date: '2025-02-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R10: Hoi An Heritage Client Tour (SUBMITTED, VND) ─────────────────────
  {
    id: I('000000000038'),
    reportId: rid('000000000010'),
    merchant: 'Morning Glory Restaurant',
    description: 'Signature Hoi An lunch — White Rose dumplings',
    amount: 64,
    currency: 'USD',
    date: '2025-04-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000039'),
    reportId: rid('000000000010'),
    merchant: 'The Cargo Club',
    description: 'Afternoon French-Vietnamese tea break',
    amount: 40,
    currency: 'USD',
    date: '2025-04-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000040'),
    reportId: rid('000000000010'),
    merchant: 'White Marble Wine Bar',
    description: 'Client wine tasting evening — Ancient Town',
    amount: 100,
    currency: 'USD',
    date: '2025-04-03',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000041'),
    reportId: rid('000000000010'),
    merchant: 'Mango Mango',
    description: 'Farewell modern Vietnamese dinner',
    amount: 86,
    currency: 'USD',
    date: '2025-04-03',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R11: Da Lat Strategy Retreat (APPROVED, VND) ──────────────────────────
  {
    id: I('000000000042'),
    reportId: rid('000000000011'),
    merchant: 'Le Chalet Dalat',
    description: 'French Alpine strategy closing dinner',
    amount: 196,
    currency: 'USD',
    date: '2025-01-05',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000043'),
    reportId: rid('000000000011'),
    merchant: 'V Cafe',
    description: 'Team brunch — Day 1',
    amount: 55,
    currency: 'USD',
    date: '2025-01-06',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000044'),
    reportId: rid('000000000011'),
    merchant: 'Quan Bia Quang Trung',
    description: 'Traditional Da Lat team dinner',
    amount: 106,
    currency: 'USD',
    date: '2025-01-06',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000045'),
    reportId: rid('000000000011'),
    merchant: 'V Cafe',
    description: 'Working lunch — OKR review session',
    amount: 51,
    currency: 'USD',
    date: '2025-01-07',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000046'),
    reportId: rid('000000000011'),
    merchant: 'Le Chalet Dalat',
    description: 'Leadership breakfast — final day',
    amount: 76,
    currency: 'USD',
    date: '2025-01-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R12: Nha Trang Retreat (REJECTED, VND) — 1 item ──────────────────────
  {
    id: I('000000000047'),
    reportId: rid('000000000012'),
    merchant: 'Sailing Club Nha Trang',
    description: 'Team beachfront dinner — customer success celebration',
    amount: 131,
    currency: 'USD',
    date: '2024-12-05',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R13: Can Tho Business Visit (APPROVED, VND) ────────────────────────────
  {
    id: I('000000000048'),
    reportId: rid('000000000013'),
    merchant: 'Nam Bo Boutique Hotel Restaurant',
    description: 'Client welcome lunch — Mekong River view',
    amount: 116,
    currency: 'USD',
    date: '2024-12-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000049'),
    reportId: rid('000000000013'),
    merchant: 'Mekong Restaurant',
    description: 'Riverside dinner with regional distributors',
    amount: 127,
    currency: 'USD',
    date: '2024-12-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000050'),
    reportId: rid('000000000013'),
    merchant: 'Nam Bo Boutique Hotel Restaurant',
    description: 'Morning coffee briefing (5 pax)',
    amount: 18,
    currency: 'USD',
    date: '2024-12-09',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000051'),
    reportId: rid('000000000013'),
    merchant: 'Mekong Restaurant',
    description: 'Farewell team lunch',
    amount: 90,
    currency: 'USD',
    date: '2024-12-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000052'),
    reportId: rid('000000000013'),
    merchant: 'Nam Bo Boutique Hotel Restaurant',
    description: 'Executive closing dinner',
    amount: 184,
    currency: 'USD',
    date: '2024-12-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R14: Vung Tau Visit (SUBMITTED, VND) ──────────────────────────────────
  {
    id: I('000000000053'),
    reportId: rid('000000000014'),
    merchant: 'Gành Hào Seafood',
    description: 'Beachside seafood lunch with platform team',
    amount: 98,
    currency: 'USD',
    date: '2025-04-07',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000054'),
    reportId: rid('000000000014'),
    merchant: 'Bạch Dinh Villa Restaurant',
    description: 'Client dinner at the historic villa',
    amount: 147,
    currency: 'USD',
    date: '2025-04-07',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000055'),
    reportId: rid('000000000014'),
    merchant: 'Gành Hào Seafood',
    description: 'Team breakfast — Day 2',
    amount: 39,
    currency: 'USD',
    date: '2025-04-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000056'),
    reportId: rid('000000000014'),
    merchant: 'Bạch Dinh Villa Restaurant',
    description: 'Platform team farewell lunch',
    amount: 112,
    currency: 'USD',
    date: '2025-04-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R15: Phu Quoc Retreat (APPROVED, VND) ─────────────────────────────────
  {
    id: I('000000000057'),
    reportId: rid('000000000015'),
    merchant: 'The Shack Phu Quoc',
    description: 'Beachfront welcome dinner — resort venue',
    amount: 212,
    currency: 'USD',
    date: '2025-02-01',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000058'),
    reportId: rid('000000000015'),
    merchant: 'Pepper Tree Restaurant',
    description: 'Leadership breakfast — strategy alignment',
    amount: 98,
    currency: 'USD',
    date: '2025-02-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000059'),
    reportId: rid('000000000015'),
    merchant: 'The Shack Phu Quoc',
    description: 'Team sundowner drinks — sunset on Long Beach',
    amount: 76,
    currency: 'USD',
    date: '2025-02-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000060'),
    reportId: rid('000000000015'),
    merchant: 'Pepper Tree Restaurant',
    description: 'OKR alignment dinner',
    amount: 188,
    currency: 'USD',
    date: '2025-02-03',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000061'),
    reportId: rid('000000000015'),
    merchant: 'The Shack Phu Quoc',
    description: 'Farewell brunch — final day',
    amount: 131,
    currency: 'USD',
    date: '2025-02-04',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R16: Hue Trip (REJECTED) — 0 items ────────────────────────────────────
  // ── R17: Tokyo Product Summit (APPROVED, JPY) ──────────────────────────────
  {
    id: I('000000000062'),
    reportId: rid('000000000017'),
    merchant: 'Narisawa',
    description: 'Summit opening gala — innovative satoyama cuisine',
    amount: 3,
    currency: 'USD',
    date: '2025-03-30',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000063'),
    reportId: rid('000000000017'),
    merchant: 'Tonki Meguro',
    description: 'Team tonkatsu lunch — Day 1',
    amount: 1,
    currency: 'USD',
    date: '2025-03-31',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000064'),
    reportId: rid('000000000017'),
    merchant: 'Tempura Kondo',
    description: 'Executive lunch — product roadmap review',
    amount: 2,
    currency: 'USD',
    date: '2025-04-01',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000065'),
    reportId: rid('000000000017'),
    merchant: 'Ukai-tei Ginza',
    description: 'Partner teppanyaki dinner',
    amount: 3,
    currency: 'USD',
    date: '2025-04-01',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000066'),
    reportId: rid('000000000017'),
    merchant: 'Sukiyabashi Jiro Honten',
    description: 'Summit farewell omakase dinner',
    amount: 5,
    currency: 'USD',
    date: '2025-04-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R18: Tokyo Partnership Dinners (SUBMITTED, JPY) ────────────────────────
  {
    id: I('000000000067'),
    reportId: rid('000000000018'),
    merchant: 'Sushi Yoshitake',
    description: 'Partner omakase — Night 1',
    amount: 4,
    currency: 'USD',
    date: '2025-04-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000068'),
    reportId: rid('000000000018'),
    merchant: 'Narisawa',
    description: 'CEO dinner with Japanese investors',
    amount: 6,
    currency: 'USD',
    date: '2025-04-11',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000069'),
    reportId: rid('000000000018'),
    merchant: 'Den',
    description: 'Kaiseki dinner — partnership contract signing',
    amount: 4,
    currency: 'USD',
    date: '2025-04-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000070'),
    reportId: rid('000000000018'),
    merchant: 'Tempura Kondo',
    description: 'Closing working lunch',
    amount: 1,
    currency: 'USD',
    date: '2025-04-13',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R19: Osaka Visit (DRAFT) — PENDING ────────────────────────────────────
  PENDING_ITEM(I('000000000071'), rid('000000000019')),
  PENDING_ITEM(I('000000000072'), rid('000000000019')),
  // ── R20: Singapore FinTech Conference (APPROVED, SGD) ─────────────────────
  {
    id: I('000000000073'),
    reportId: rid('000000000020'),
    merchant: 'Odette',
    description: 'Conference gala dinner',
    amount: 620,
    currency: 'USD',
    date: '2025-03-12',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000074'),
    reportId: rid('000000000020'),
    merchant: 'Hawker Chan',
    description: 'Team hawker lunch — Michelin street food',
    amount: 95,
    currency: 'USD',
    date: '2025-03-13',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000075'),
    reportId: rid('000000000020'),
    merchant: 'Burnt Ends',
    description: 'FinTech networking dinner — modern BBQ',
    amount: 480,
    currency: 'USD',
    date: '2025-03-13',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000076'),
    reportId: rid('000000000020'),
    merchant: 'Jumbo Seafood Robertson Quay',
    description: 'Chilli crab celebration dinner',
    amount: 560,
    currency: 'USD',
    date: '2025-03-14',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000077'),
    reportId: rid('000000000020'),
    merchant: 'Din Tai Fung Paragon',
    description: 'Farewell dim sum brunch',
    amount: 215,
    currency: 'USD',
    date: '2025-03-15',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R21: Singapore Regional HQ (SUBMITTED, SGD) ────────────────────────────
  {
    id: I('000000000078'),
    reportId: rid('000000000021'),
    merchant: 'Candlenut',
    description: 'Peranakan business dinner',
    amount: 380,
    currency: 'USD',
    date: '2025-04-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000079'),
    reportId: rid('000000000021'),
    merchant: 'Din Tai Fung Paragon',
    description: 'HQ team lunch',
    amount: 190,
    currency: 'USD',
    date: '2025-04-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000080'),
    reportId: rid('000000000021'),
    merchant: 'Burnt Ends',
    description: 'Stakeholder dinner',
    amount: 420,
    currency: 'USD',
    date: '2025-04-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000081'),
    reportId: rid('000000000021'),
    merchant: 'Hawker Chan',
    description: 'Working lunch — product sync',
    amount: 88,
    currency: 'USD',
    date: '2025-04-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R22: Singapore Client Entertainment (DRAFT) — PENDING ─────────────────
  PENDING_ITEM(I('000000000082'), rid('000000000022')),
  PENDING_ITEM(I('000000000083'), rid('000000000022')),
  // ── R23: Bangkok SEA Meeting (APPROVED, THB) ───────────────────────────────
  {
    id: I('000000000084'),
    reportId: rid('000000000023'),
    merchant: 'Gaggan Anand',
    description: 'Summit opening gala — progressive Indian cuisine',
    amount: 1,
    currency: 'USD',
    date: '2025-02-18',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000085'),
    reportId: rid('000000000023'),
    merchant: 'Nahm',
    description: 'Traditional Thai royal cuisine dinner',
    amount: 1,
    currency: 'USD',
    date: '2025-02-19',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000086'),
    reportId: rid('000000000023'),
    merchant: 'Jay Fai',
    description: 'Michelin street food lunch — signature crab omelette',
    amount: 0,
    currency: 'USD',
    date: '2025-02-19',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000087'),
    reportId: rid('000000000023'),
    merchant: 'Bo.lan',
    description: 'Organic Thai dinner — sustainability-themed',
    amount: 0,
    currency: 'USD',
    date: '2025-02-20',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000088'),
    reportId: rid('000000000023'),
    merchant: 'Paste Bangkok',
    description: 'Farewell modern Thai lunch',
    amount: 0,
    currency: 'USD',
    date: '2025-02-20',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R24: Kuala Lumpur HQ Visit (APPROVED, MYR) ────────────────────────────
  {
    id: I('000000000089'),
    reportId: rid('000000000024'),
    merchant: 'Dewakan',
    description: 'Modern Malaysian fine dining — HQ welcome dinner',
    amount: 850,
    currency: 'USD',
    date: '2025-01-22',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000090'),
    reportId: rid('000000000024'),
    merchant: 'Nadodi',
    description: 'Progressive South Indian business lunch',
    amount: 480,
    currency: 'USD',
    date: '2025-01-23',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000091'),
    reportId: rid('000000000024'),
    merchant: 'Bref by Darren Chin',
    description: 'French fine dining client dinner',
    amount: 0,
    currency: 'USD',
    date: '2025-01-23',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000092'),
    reportId: rid('000000000024'),
    merchant: 'DC Restaurant',
    description: 'Partnership dinner — Petronas Towers view',
    amount: 0,
    currency: 'USD',
    date: '2025-01-24',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000093'),
    reportId: rid('000000000024'),
    merchant: 'Dewakan',
    description: 'SEA leadership farewell brunch',
    amount: 680,
    currency: 'USD',
    date: '2025-01-25',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R25: Bangkok Client Relations (DRAFT) — PENDING ───────────────────────
  PENDING_ITEM(I('000000000094'), rid('000000000025')),
  PENDING_ITEM(I('000000000095'), rid('000000000025')),
  // ── R26: Seoul Tech Summit (APPROVED, KRW) ─────────────────────────────────
  {
    id: I('000000000096'),
    reportId: rid('000000000026'),
    merchant: 'Gaon',
    description: 'Summit opening dinner — traditional Korean',
    amount: 13,
    currency: 'USD',
    date: '2025-03-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000097'),
    reportId: rid('000000000026'),
    merchant: 'Jungsik',
    description: 'Modern Korean executive lunch',
    amount: 8,
    currency: 'USD',
    date: '2025-03-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000098'),
    reportId: rid('000000000026'),
    merchant: 'Mingles',
    description: 'Innovation dinner — Korean fusion',
    amount: 9,
    currency: 'USD',
    date: '2025-03-09',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000099'),
    reportId: rid('000000000026'),
    merchant: 'Kwon Sook-soo',
    description: 'Traditional Korean farewell dinner',
    amount: 10,
    currency: 'USD',
    date: '2025-03-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000100'),
    reportId: rid('000000000026'),
    merchant: 'Gwangjang Market',
    description: 'Team immersive market lunch — bindaetteok & mung bean',
    amount: 2,
    currency: 'USD',
    date: '2025-03-10',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R27: Paris Partnership (SUBMITTED, EUR) ────────────────────────────────
  {
    id: I('000000000101'),
    reportId: rid('000000000027'),
    merchant: 'Café de Flore',
    description: 'Partnership kickoff coffee — Saint-Germain-des-Prés',
    amount: 68,
    currency: 'USD',
    date: '2025-04-01',
    category: 'Coffee & Refreshments',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000102'),
    reportId: rid('000000000027'),
    merchant: 'Septime',
    description: 'Business lunch — Bastille',
    amount: 185,
    currency: 'USD',
    date: '2025-04-01',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000103'),
    reportId: rid('000000000027'),
    merchant: 'Le Jules Verne',
    description: 'Executive dinner — Eiffel Tower',
    amount: 420,
    currency: 'USD',
    date: '2025-04-02',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000104'),
    reportId: rid('000000000027'),
    merchant: 'Le Comptoir du Relais',
    description: 'Casual farewell brasserie dinner',
    amount: 140,
    currency: 'USD',
    date: '2025-04-03',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R28: London Investor Relations (APPROVED, GBP) ────────────────────────
  {
    id: I('000000000105'),
    reportId: rid('000000000028'),
    merchant: 'The Ledbury',
    description: 'Investor welcome dinner — Notting Hill',
    amount: 480,
    currency: 'USD',
    date: '2025-04-05',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000106'),
    reportId: rid('000000000028'),
    merchant: 'Dishoom Shoreditch',
    description: 'Team Indian brunch',
    amount: 165,
    currency: 'USD',
    date: '2025-04-06',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000107'),
    reportId: rid('000000000028'),
    merchant: 'Ottolenghi Islington',
    description: 'Working lunch — investor deck preparation',
    amount: 210,
    currency: 'USD',
    date: '2025-04-06',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000108'),
    reportId: rid('000000000028'),
    merchant: 'Sketch',
    description: 'Afternoon tea with institutional investor — Mayfair',
    amount: 320,
    currency: 'USD',
    date: '2025-04-07',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000109'),
    reportId: rid('000000000028'),
    merchant: 'Duck & Waffle',
    description: 'Closing breakfast — 40th floor City views',
    amount: 195,
    currency: 'USD',
    date: '2025-04-08',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  // ── R29: Berlin Conference (DRAFT) — PENDING ──────────────────────────────
  PENDING_ITEM(I('000000000110'), rid('000000000029')),
  PENDING_ITEM(I('000000000111'), rid('000000000029')),
  // ── R30: New York Launch (SUBMITTED, USD) ─────────────────────────────────
  {
    id: I('000000000112'),
    reportId: rid('000000000030'),
    merchant: 'Le Bernardin',
    description: 'Launch dinner with NYC investors',
    amount: 850,
    currency: 'USD',
    date: '2025-04-14',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000113'),
    reportId: rid('000000000030'),
    merchant: "Katz's Delicatessen",
    description: 'Iconic team lunch — Lower East Side',
    amount: 145,
    currency: 'USD',
    date: '2025-04-15',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000114'),
    reportId: rid('000000000030'),
    merchant: 'Eleven Madison Park',
    description: 'Stakeholder dinner',
    amount: 780,
    currency: 'USD',
    date: '2025-04-15',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
  {
    id: I('000000000115'),
    reportId: rid('000000000030'),
    merchant: 'Balthazar',
    description: 'Farewell SoHo brasserie dinner',
    amount: 380,
    currency: 'USD',
    date: '2025-04-16',
    category: 'Meals & Entertainment',
    aiStatus: 'COMPLETED',
    aiExtracted: true,
  },
];

export const seedItems: readonly SeedItem[] = [
  ...baseSeedItems,
  ...generateMissingReportItems(baseSeedItems),
];
